[package]
name = "otellme-ingestor"
authors.workspace = true
repository.workspace = true
exclude.workspace = true
edition.workspace = true
readme.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
otellme-utils = { path = "../utils", version = "0" }

anyhow.workspace = true
async-trait.workspace = true
opentelemetry-proto = { workspace = true, features = ["gen-tonic", "logs"] }
tracing.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tonic = { workspace = true, default-features = false, features = ["prost", "transport"] }
